// Tenancy RBAC

export const MEMBERSHIP_STATUS_LIST = [
  "active",
  "invited",
  "suspended",
] as const;

export const DEFAULT_ROLE_LIST = [
  "OWNER",
  "ADMIN",
  "MANAGER",
  "WAREHOUSE_MANAGER",
  "PRODUCTION_MANAGER",
  "QUALITY_MANAGER",
  "QUALITY_OFFICER",
  "HR_MANAGER",
  "HR_OFFICER",
  "SALES_MANAGER",
  "SALES_OFFICER",
  "FINANCE_MANAGER",
  "FINANCE_OFFICER",
  "EMPLOYEE",
] as const;

export const PERMISSION_LIST = [
  "organization.read",
  "organization.update",
  "audit.read",
  "membership.read",
  "membership.create",
  "membership.update",
  "membership.delete",
  "role.read",
  "role.create",
  "role.update",
  "role.delete",
  "inventory.item.read",
  "inventory.item.create",
  "inventory.item.update",
  "inventory.item.archive",
  "inventory.warehouse.read",
  "inventory.warehouse.create",
  "inventory.warehouse.update",
  "inventory.lot.read",
  "inventory.lot.create",
  "inventory.lot.update",
  "inventory.stock.read",
  "inventory.stock.receive",
  "inventory.stock.issue",
  "inventory.stock.transfer",
  "inventory.stock.adjust",
  "inventory.stock.return",
  "inventory.movement.read",
  "inventory.reservation.read",
  "inventory.reservation.create",
  "inventory.reservation.release",
  "inventory.reservation.consume",
  "manufacturing.bom.read",
  "manufacturing.bom.create",
  "manufacturing.bom.update",
  "manufacturing.bom.approve",
  "manufacturing.production.read",
  "manufacturing.production.create",
  "manufacturing.production.approve",
  "manufacturing.production.execute",
  "quality.inspection.read",
  "quality.inspection.create",
  "quality.inspection.review",
  "quality.inventory.release",
  "quality.inventory.reject",
  "traceability.read",
  "hr.employee.read",
  "hr.employee.create",
  "hr.employee.update",
  "hr.employee.archive",
  "hr.attendance.read",
  "hr.attendance.clock",
  "hr.attendance.manage",
  "hr.schedule.read",
  "hr.schedule.create",
  "hr.schedule.update",
  "kiosk.read",
  "kiosk.create",
  "kiosk.activate",
  "kiosk.deactivate",
  "sales.customer.read",
  "sales.customer.create",
  "sales.customer.update",
  "sales.order.read",
  "sales.order.create",
  "sales.order.confirm",
  "sales.order.cancel",
  "sales.commission.read",
  "sales.commission.approve",
  "finance.invoice.read",
  "finance.invoice.create",
  "finance.invoice.issue",
  "finance.invoice.void",
  "finance.payment.read",
  "finance.payment.create",
  "finance.cost.read",
  "finance.cost.create",
  "finance.cost.update",
] as const;

export const DEFAULT_ROLE_PERMISSIONS: Record<
  (typeof DEFAULT_ROLE_LIST)[number],
  (typeof PERMISSION_LIST)[number][]
> = {
  OWNER: [
    "organization.read",
    "organization.update",
    "audit.read",
    "membership.read",
    "membership.create",
    "membership.update",
    "membership.delete",
    "role.read",
    "role.create",
    "role.update",
    "role.delete",
    "inventory.item.read",
    "inventory.item.create",
    "inventory.item.update",
    "inventory.item.archive",
    "inventory.warehouse.read",
    "inventory.warehouse.create",
    "inventory.warehouse.update",
    "inventory.lot.read",
    "inventory.lot.create",
    "inventory.lot.update",
    "inventory.stock.read",
    "inventory.stock.receive",
    "inventory.stock.issue",
    "inventory.stock.transfer",
    "inventory.stock.adjust",
    "inventory.stock.return",
    "inventory.movement.read",
    "inventory.reservation.read",
    "inventory.reservation.create",
    "inventory.reservation.release",
    "inventory.reservation.consume",
    "manufacturing.bom.read",
    "manufacturing.bom.create",
    "manufacturing.bom.update",
    "manufacturing.bom.approve",
    "manufacturing.production.read",
    "manufacturing.production.create",
    "manufacturing.production.approve",
    "manufacturing.production.execute",
    "quality.inspection.read",
    "quality.inspection.create",
    "quality.inspection.review",
    "quality.inventory.release",
    "quality.inventory.reject",
    "traceability.read",
    "hr.employee.read",
    "hr.employee.create",
    "hr.employee.update",
    "hr.employee.archive",
    "hr.attendance.read",
    "hr.attendance.clock",
    "hr.attendance.manage",
    "hr.schedule.read",
    "hr.schedule.create",
    "hr.schedule.update",
    "kiosk.read",
    "kiosk.create",
    "kiosk.activate",
    "kiosk.deactivate",
    "sales.customer.read",
    "sales.customer.create",
    "sales.customer.update",
    "sales.order.read",
    "sales.order.create",
    "sales.order.confirm",
    "sales.order.cancel",
    "sales.commission.read",
    "sales.commission.approve",
    "finance.invoice.read",
    "finance.invoice.create",
    "finance.invoice.issue",
    "finance.invoice.void",
    "finance.payment.read",
    "finance.payment.create",
    "finance.cost.read",
    "finance.cost.create",
    "finance.cost.update",
  ],
  ADMIN: [
    "organization.read",
    "organization.update",
    "audit.read",
    "membership.read",
    "membership.create",
    "membership.update",
    "membership.delete",
    "role.read",
    "role.create",
    "role.update",
    "role.delete",
    "inventory.item.read",
    "inventory.item.create",
    "inventory.item.update",
    "inventory.item.archive",
    "inventory.warehouse.read",
    "inventory.warehouse.create",
    "inventory.warehouse.update",
    "inventory.lot.read",
    "inventory.lot.create",
    "inventory.lot.update",
    "inventory.stock.read",
    "inventory.stock.receive",
    "inventory.stock.issue",
    "inventory.stock.transfer",
    "inventory.stock.adjust",
    "inventory.stock.return",
    "inventory.movement.read",
    "inventory.reservation.read",
    "inventory.reservation.create",
    "inventory.reservation.release",
    "inventory.reservation.consume",
    "manufacturing.bom.read",
    "manufacturing.bom.create",
    "manufacturing.bom.update",
    "manufacturing.bom.approve",
    "manufacturing.production.read",
    "manufacturing.production.create",
    "manufacturing.production.approve",
    "manufacturing.production.execute",
    "quality.inspection.read",
    "quality.inspection.create",
    "quality.inspection.review",
    "quality.inventory.release",
    "quality.inventory.reject",
    "traceability.read",
    "hr.employee.read",
    "hr.employee.create",
    "hr.employee.update",
    "hr.employee.archive",
    "hr.attendance.read",
    "hr.attendance.clock",
    "hr.attendance.manage",
    "hr.schedule.read",
    "hr.schedule.create",
    "hr.schedule.update",
    "kiosk.read",
    "kiosk.create",
    "kiosk.activate",
    "kiosk.deactivate",
    "sales.customer.read",
    "sales.customer.create",
    "sales.customer.update",
    "sales.order.read",
    "sales.order.create",
    "sales.order.confirm",
    "sales.order.cancel",
    "sales.commission.read",
    "sales.commission.approve",
    "finance.invoice.read",
    "finance.invoice.create",
    "finance.invoice.issue",
    "finance.invoice.void",
    "finance.payment.read",
    "finance.payment.create",
    "finance.cost.read",
    "finance.cost.create",
    "finance.cost.update",
  ],
  MANAGER: [
    "organization.read",
    "membership.read",
    "role.read",
    "inventory.item.read",
    "inventory.warehouse.read",
    "inventory.lot.read",
    "inventory.stock.read",
    "inventory.movement.read",
    "inventory.reservation.read",
    "manufacturing.bom.read",
    "manufacturing.production.read",
    "quality.inspection.read",
    "traceability.read",
    "hr.employee.read",
    "hr.attendance.read",
    "hr.schedule.read",
  ],
  WAREHOUSE_MANAGER: [
    "organization.read",
    "inventory.item.read",
    "inventory.item.create",
    "inventory.item.update",
    "inventory.warehouse.read",
    "inventory.warehouse.create",
    "inventory.warehouse.update",
    "inventory.lot.read",
    "inventory.lot.create",
    "inventory.lot.update",
    "inventory.stock.read",
    "inventory.stock.receive",
    "inventory.stock.issue",
    "inventory.stock.transfer",
    "inventory.stock.adjust",
    "inventory.stock.return",
    "inventory.movement.read",
    "inventory.reservation.read",
    "inventory.reservation.create",
    "inventory.reservation.release",
    "inventory.reservation.consume",
    "manufacturing.bom.read",
    "manufacturing.production.read",
    "quality.inspection.read",
    "traceability.read",
  ],
  PRODUCTION_MANAGER: [
    "organization.read",
    "inventory.item.read",
    "inventory.warehouse.read",
    "inventory.lot.read",
    "inventory.stock.read",
    "inventory.movement.read",
    "inventory.reservation.read",
    "inventory.reservation.create",
    "inventory.reservation.release",
    "inventory.reservation.consume",
    "manufacturing.bom.read",
    "manufacturing.bom.create",
    "manufacturing.bom.update",
    "manufacturing.bom.approve",
    "manufacturing.production.read",
    "manufacturing.production.create",
    "manufacturing.production.approve",
    "manufacturing.production.execute",
    "quality.inspection.read",
    "traceability.read",
  ],
  QUALITY_MANAGER: [
    "organization.read",
    "inventory.item.read",
    "inventory.warehouse.read",
    "inventory.lot.read",
    "inventory.lot.update",
    "inventory.stock.read",
    "inventory.movement.read",
    "manufacturing.bom.read",
    "manufacturing.production.read",
    "quality.inspection.read",
    "quality.inspection.create",
    "quality.inspection.review",
    "quality.inventory.release",
    "quality.inventory.reject",
    "traceability.read",
  ],
  QUALITY_OFFICER: [
    "organization.read",
    "inventory.item.read",
    "inventory.warehouse.read",
    "inventory.lot.read",
    "inventory.stock.read",
    "inventory.movement.read",
    "manufacturing.production.read",
    "quality.inspection.read",
    "quality.inspection.create",
    "quality.inspection.review",
    "quality.inventory.release",
    "quality.inventory.reject",
    "traceability.read",
  ],
  HR_MANAGER: [
    "organization.read",
    "audit.read",
    "hr.employee.read",
    "hr.employee.create",
    "hr.employee.update",
    "hr.employee.archive",
    "hr.attendance.read",
    "hr.attendance.clock",
    "hr.attendance.manage",
    "hr.schedule.read",
    "hr.schedule.create",
    "hr.schedule.update",
    "kiosk.read",
    "kiosk.create",
    "kiosk.activate",
    "kiosk.deactivate",
  ],
  HR_OFFICER: [
    "organization.read",
    "hr.employee.read",
    "hr.employee.create",
    "hr.employee.update",
    "hr.attendance.read",
    "hr.schedule.read",
    "kiosk.read",
    "kiosk.create",
    "kiosk.activate",
    "kiosk.deactivate",
  ],
  SALES_MANAGER: [
    "organization.read",
    "membership.read",
    "inventory.item.read",
    "inventory.warehouse.read",
    "inventory.stock.read",
    "inventory.reservation.read",
    "sales.customer.read",
    "sales.customer.create",
    "sales.customer.update",
    "sales.order.read",
    "sales.order.create",
    "sales.order.confirm",
    "sales.order.cancel",
    "sales.commission.read",
    "sales.commission.approve",
    "finance.invoice.read",
  ],
  SALES_OFFICER: [
    "organization.read",
    "inventory.item.read",
    "inventory.warehouse.read",
    "inventory.stock.read",
    "inventory.reservation.read",
    "sales.customer.read",
    "sales.customer.create",
    "sales.customer.update",
    "sales.order.read",
    "sales.order.create",
  ],
  FINANCE_MANAGER: [
    "organization.read",
    "membership.read",
    "audit.read",
    "inventory.item.read",
    "sales.customer.read",
    "sales.order.read",
    "sales.commission.read",
    "finance.invoice.read",
    "finance.invoice.create",
    "finance.invoice.issue",
    "finance.invoice.void",
    "finance.payment.read",
    "finance.payment.create",
    "finance.cost.read",
    "finance.cost.create",
    "finance.cost.update",
  ],
  FINANCE_OFFICER: [
    "organization.read",
    "inventory.item.read",
    "sales.customer.read",
    "sales.order.read",
    "finance.invoice.read",
    "finance.invoice.create",
    "finance.payment.read",
    "finance.payment.create",
    "finance.cost.read",
    "finance.cost.create",
  ],
  EMPLOYEE: [
    "organization.read",
    "inventory.item.read",
    "inventory.warehouse.read",
    "inventory.stock.read",
    "hr.attendance.clock",
  ],
};

export const AUDIT_PAGE_LIMIT_MAXIMUM = 100;
export const AUDIT_PAGE_LIMIT_MINIMUM = 10;
export const AUDIT_DEFAULT_PAGE_SIZE = 25;
export const AUDIT_DEFAULT_PAGE = 1;

export const DEFAULT_ROLE_NAMES: Record<
  (typeof DEFAULT_ROLE_LIST)[number],
  string
> = {
  OWNER: "Owner",
  ADMIN: "Administrator",
  MANAGER: "Manager",
  WAREHOUSE_MANAGER: "Warehouse Manager",
  PRODUCTION_MANAGER: "Production Manager",
  QUALITY_MANAGER: "Quality Manager",
  QUALITY_OFFICER: "Quality Officer",
  HR_MANAGER: "HR Manager",
  HR_OFFICER: "HR Officer",
  SALES_MANAGER: "Sales Manager",
  SALES_OFFICER: "Sales Officer",
  FINANCE_MANAGER: "Finance Manager",
  FINANCE_OFFICER: "Finance Officer",
  EMPLOYEE: "Employee",
};

export const DEFAULT_ROLE_DESCRIPTIONS: Record<
  (typeof DEFAULT_ROLE_LIST)[number],
  string
> = {
  OWNER: "Full control of the organization",
  ADMIN: "Manage everything except organization ownership",
  MANAGER: "Read-only overview across all modules",
  WAREHOUSE_MANAGER: "Inventory and warehouse operations",
  PRODUCTION_MANAGER: "Manufacturing and production orders",
  QUALITY_MANAGER: "Quality control and lot decisions",
  QUALITY_OFFICER: "Run and record inspections",
  HR_MANAGER: "Workforce, attendance and schedules",
  HR_OFFICER: "Employee records and attendance",
  SALES_MANAGER: "Customers, orders and commissions",
  SALES_OFFICER: "Customers and orders",
  FINANCE_MANAGER: "Invoices, payments and costs",
  FINANCE_OFFICER: "Invoices and payments",
  EMPLOYEE: "Read-only stock view and clock in/out",
};

export const ROLE_GROUPS: {
  label: string;
  roles: (typeof DEFAULT_ROLE_LIST)[number][];
}[] = [
  {
    label: "Platform-wide",
    roles: ["OWNER", "ADMIN", "MANAGER", "EMPLOYEE"],
  },
  {
    label: "Workforce",
    roles: ["HR_MANAGER", "HR_OFFICER"],
  },
  {
    label: "Inventory & Warehouse",
    roles: ["WAREHOUSE_MANAGER"],
  },
  {
    label: "Manufacturing",
    roles: ["PRODUCTION_MANAGER"],
  },
  {
    label: "Quality",
    roles: ["QUALITY_MANAGER", "QUALITY_OFFICER"],
  },
  {
    label: "Sales",
    roles: ["SALES_MANAGER", "SALES_OFFICER"],
  },
  {
    label: "Finance",
    roles: ["FINANCE_MANAGER", "FINANCE_OFFICER"],
  },
];

export const PERMISSION_DESCRIPTIONS: Record<
  (typeof PERMISSION_LIST)[number],
  string
> = {
  "organization.read": "View organization details",
  "organization.update": "Update organization details",
  "audit.read": "View audit logs",
  "membership.read": "View organization members",
  "membership.create": "Add members to the organization",
  "membership.update": "Change member roles or status",
  "membership.delete": "Remove members from the organization",
  "role.read": "View organization roles",
  "role.create": "Create organization roles",
  "role.update": "Change role permissions",
  "role.delete": "Delete organization roles",
  "inventory.item.read": "View inventory items",
  "inventory.item.create": "Create inventory items",
  "inventory.item.update": "Update inventory items",
  "inventory.item.archive": "Archive inventory items",
  "inventory.warehouse.read": "View warehouses and locations",
  "inventory.warehouse.create": "Create warehouses",
  "inventory.warehouse.update": "Update warehouses",
  "inventory.lot.read": "View lots",
  "inventory.lot.create": "Create lots",
  "inventory.lot.update": "Update lot quality status",
  "inventory.stock.read": "View stock balances",
  "inventory.stock.receive": "Receive stock into a warehouse",
  "inventory.stock.issue": "Issue stock from a warehouse",
  "inventory.stock.transfer": "Transfer stock between locations",
  "inventory.stock.adjust": "Adjust stock quantities",
  "inventory.stock.return": "Return stock to a supplier",
  "inventory.movement.read": "View inventory movement ledger",
  "inventory.reservation.read": "View stock reservations",
  "inventory.reservation.create": "Reserve stock",
  "inventory.reservation.release": "Release stock reservations",
  "inventory.reservation.consume": "Consume stock reservations",
  "manufacturing.bom.read": "View bills of materials",
  "manufacturing.bom.create": "Create bills of materials",
  "manufacturing.bom.update": "Update draft bills of materials",
  "manufacturing.bom.approve": "Approve bills of materials",
  "manufacturing.production.read": "View production orders and batches",
  "manufacturing.production.create": "Create production orders",
  "manufacturing.production.approve": "Approve production orders",
  "manufacturing.production.execute": "Execute production (consume, return, output)",
  "quality.inspection.read": "View quality inspections",
  "quality.inspection.create": "Create quality inspections and record test results",
  "quality.inspection.review": "Review (complete) quality inspections",
  "quality.inventory.release": "Release quarantined lots to released stock",
  "quality.inventory.reject": "Reject quarantined lots",
  "traceability.read": "Trace lots forward and reverse through production",
  "hr.employee.read": "View employees, departments, positions and contacts",
  "hr.employee.create": "Create employees, departments, positions and contacts",
  "hr.employee.update": "Update employees, departments, positions and contacts",
  "hr.employee.archive": "Archive and restore employees",
  "hr.attendance.read": "View attendance events",
  "hr.attendance.clock": "Record own attendance (clock in/out, breaks)",
  "hr.attendance.manage": "Record attendance on behalf of employees",
  "hr.schedule.read": "View shifts and employee schedules",
  "hr.schedule.create": "Create shifts and assign them to employees",
  "hr.schedule.update": "Update shifts and schedules",
  "kiosk.read": "View kiosk devices",
  "kiosk.create": "Register new kiosk devices",
  "kiosk.activate": "Activate kiosk devices",
  "kiosk.deactivate": "Deactivate kiosk devices",
  "sales.customer.read": "View customers, contacts and addresses",
  "sales.customer.create": "Create customers",
  "sales.customer.update": "Update customers, contacts and addresses",
  "sales.order.read": "View sales orders and stock availability",
  "sales.order.create": "Create sales orders",
  "sales.order.confirm": "Confirm sales orders (reserves released stock)",
  "sales.order.cancel": "Cancel sales orders",
  "sales.commission.read": "View commission rules and records",
  "sales.commission.approve": "Approve and manage commissions",
  "finance.invoice.read": "View invoices",
  "finance.invoice.create": "Generate invoices from sales orders",
  "finance.invoice.issue": "Issue invoices to customers",
  "finance.invoice.void": "Void invoices",
  "finance.payment.read": "View payments and allocations",
  "finance.payment.create": "Record payments against invoices",
  "finance.cost.read": "View costs and cost centers",
  "finance.cost.create": "Create costs and cost centers",
  "finance.cost.update": "Update costs and cost centers",
};

export const PERMISSION_CACHE_TTL_SECONDS = 60;

export const REQUEST_ID_HEADER = "x-request-id";
export const ORGANIZATION_HEADER = "x-organization-id";
