// Test-only X.509 fixtures (P-256): a self-signed root and a leaf it issued.
// Generated with openssl; validity ~100 years. Not real Google attestation roots.

export const TEST_ATTESTATION_ROOT_CERT =
  'MIIBmDCCAT2gAwIBAgIUX8rEL4I+IMBb7aawXIsjIzQgpvMwCgYIKoZIzj0EAwIw' +
  'IDEeMBwGA1UEAwwVVGVzdCBBdHRlc3RhdGlvbiBSb290MCAXDTI2MTAxMDA4NDk1' +
  'OFoYDzIxMjYwOTE2MDg0OTU4WjAgMR4wHAYDVQQDDBVUZXN0IEF0dGVzdGF0aW9u' +
  'IFJvb3QwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARu0VKiP0WS9HCfoz3hkbK5' +
  'MWH8w1Eq+TQvCi9y7mI3rxS368OYUupxurRTl6KTAkrAu+hrQZZlIG1+e2FXgrK5' +
  'o1MwUTAdBgNVHQ4EFgQUp9NyNlk+2vCRwJ2awICJVkYo1AwwHwYDVR0jBBgwFoAU' +
  'p9NyNlk+2vCRwJ2awICJVkYo1AwwDwYDVR0TAQH/BAUwAwEB/zAKBggqhkjOPQQD' +
  'AgNJADBGAiEA8o+d6H0apyHk8OAy40rFmgPPBUzc7eDbGAlqrFxrTE4CIQDtneae' +
  'niUZuuNnPT9dY24cncPvPf+0N/EBhBM/D9sA5A==';

export const TEST_ATTESTATION_LEAF_CERT =
  'MIIBhTCCASugAwIBAgIUKQFMLIFD5yhDMy9eBqDvTY1+v5owCgYIKoZIzj0EAwIw' +
  'IDEeMBwGA1UEAwwVVGVzdCBBdHRlc3RhdGlvbiBSb290MCAXDTI2MTAxMDA4NDk1' +
  'OFoYDzIxMjYwOTE2MDg0OTU4WjAfMR0wGwYDVQQDDBRBbmRyb2lkIEtleXN0b3Jl' +
  'IEtleTBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABGwPTJictP9gEWCOfD2wVz9n' +
  'WInamL0e+F3V3aoReSva/PoN5THKXjJgByMuT598LkVjZDNsd5plJzpdPgNdYpWj' +
  'QjBAMB0GA1UdDgQWBBTG80/9C1kxu+8D+bXeThnSUft7PzAfBgNVHSMEGDAWgBSn' +
  '03I2WT7a8JHAnZrAgIlWRijUDDAKBggqhkjOPQQDAgNIADBFAiA7QMxCKkzzR5KR' +
  'kBszvUcFoB6mQ/oLLP62QRT9+INi6QIhAPeyfOlR/fuJ7JO/yfy/ZLERS/Y3Qg0q' +
  '4D/nYp1gLly2';
