
from __future__ import annotations

from app.core.enums import DataDomain

MOCK_KNOWLEDGE_DOCUMENTS: tuple[dict[str, object], ...] = (
    {
        "doc_id": "KB-001",
        "title": "Attendance Policy",
        "domain": DataDomain.HR.value,
        "content": (
            "Employees must clock in between 7:30 AM and 8:30 AM. "
            "Late arrivals beyond 8:30 AM are marked as late. "
            "Three late arrivals in a month require HR review. "
            "Overtime must be approved by the department manager in advance."
        ),
        "category": "policy",
        "tags": ["attendance", "late", "overtime", "clock-in"],
    },
    {
        "doc_id": "KB-002",
        "title": "Production Line Efficiency Targets",
        "domain": DataDomain.PRODUCTION.value,
        "content": (
            "Each production line has a daily target based on product type. "
            "Efficiency below 95% triggers a review. Efficiency below 70% "
            "requires immediate intervention. Downtime should be kept under "
            "30 minutes per shift per line."
        ),
        "category": "targets",
        "tags": ["efficiency", "target", "downtime", "review"],
    },
    {
        "doc_id": "KB-003",
        "title": "Inventory Reorder Policy",
        "domain": DataDomain.INVENTORY.value,
        "content": (
            "Items at or below reorder level must be flagged for reordering. "
            "Critical items (safety stock) should maintain 2 weeks of cover. "
            "Slow-moving items (90+ days cover) should be reviewed for "
            "potential write-down or promotion."
        ),
        "category": "policy",
        "tags": ["reorder", "safety-stock", "slow-moving", "stock"],
    },
    {
        "doc_id": "KB-004",
        "title": "Preventive Maintenance Schedule",
        "domain": DataDomain.MAINTENANCE.value,
        "content": (
            "Preventive maintenance is scheduled based on machine hours "
            "or calendar time, whichever comes first. High-criticality "
            "machines require monthly inspection. Medium-criticality machines "
            "require quarterly inspection. All maintenance must be logged "
            "in the maintenance module."
        ),
        "category": "schedule",
        "tags": ["preventive", "inspection", "criticality", "schedule"],
    },
    {
        "doc_id": "KB-005",
        "title": "Financial Reporting Requirements",
        "domain": DataDomain.FINANCE.value,
        "content": (
            "Monthly financial reports must be generated by the 5th business day. "
            "Overdue invoices older than 30 days require escalation to management. "
            "Budget variances exceeding 10% require explanation and corrective "
            "action plan."
        ),
        "category": "reporting",
        "tags": ["reporting", "overdue", "invoice", "budget", "variance"],
    },
    {
        "doc_id": "KB-006",
        "title": "Procurement Approval Workflow",
        "domain": DataDomain.PROCUREMENT.value,
        "content": (
            "Purchase orders under ETB 50,000 require manager approval. "
            "Orders between ETB 50,000 and ETB 200,000 require director approval. "
            "Orders above ETB 200,000 require executive approval. "
            "All POs must have an expected delivery date."
        ),
        "category": "workflow",
        "tags": ["purchase-order", "approval", "workflow", "threshold"],
    },
    {
        "doc_id": "KB-007",
        "title": "Quality Control Standards",
        "domain": DataDomain.PRODUCTION.value,
        "content": (
            "Reject rate should be kept below 2% for all products. "
            "Rejected units must be documented with root cause analysis. "
            "Quality checks are performed at the end of each shift. "
            "Patterns in rejects trigger line-wide quality reviews."
        ),
        "category": "quality",
        "tags": ["quality", "reject", "root-cause", "shift"],
    },
    {
        "doc_id": "KB-008",
        "title": "Safety Protocols",
        "domain": DataDomain.MAINTENANCE.value,
        "content": (
            "All maintenance work requires Lockout/Tagout (LOTO) procedures. "
            "Personal Protective Equipment (PPE) is mandatory in production areas. "
            "Machine breakdowns must be reported within 15 minutes. "
            "Emergency stop buttons must be tested weekly."
        ),
        "category": "safety",
        "tags": ["safety", "loto", "ppe", "breakdown"],
    },
)


def mock_knowledge_documents() -> list[dict[str, object]]:
    return [dict(document) for document in MOCK_KNOWLEDGE_DOCUMENTS]
